"""Document writer for creating output .docx files with counterarguments."""

from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from ..models import LegalDocument
from ..utils import get_logger

logger = get_logger(__name__)


class DocumentWriter:
    """Writer for creating formatted .docx output with claims and counterarguments."""

    def __init__(self):
        """Initialize the document writer."""
        pass

    def write_table_format(self, legal_doc: LegalDocument, output_path: Path) -> None:
        """Write document in table format with claims and counterarguments side-by-side.

        Args:
            legal_doc: LegalDocument with claims and counterarguments
            output_path: Path where output document will be saved
        """
        logger.info(f"Writing output document to: {output_path}")

        # Create new document
        doc = Document()

        # Add title
        title = doc.add_heading("Legal Argument Analysis - Counterarguments", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add metadata section
        self._add_metadata_section(doc, legal_doc)

        # Add separator
        doc.add_paragraph()

        # Add instructions
        instructions = doc.add_paragraph()
        instructions.add_run(
            "This document contains counterarguments to claims identified in your research paper. "
            "Each row presents an original claim alongside potential counterarguments for your consideration."
        ).italic = True

        doc.add_paragraph()

        # Get claims with counterarguments
        claims_with_counter = legal_doc.get_claims_with_counterarguments()

        if not claims_with_counter:
            doc.add_paragraph("No counterarguments were generated.")
            doc.save(str(output_path))
            logger.warning("No counterarguments to write")
            return

        # Create table for each claim
        for idx, claim in enumerate(claims_with_counter, 1):
            # Add claim number heading
            doc.add_heading(f"Claim {idx}", level=2)

            # Create table with 2 columns
            table = doc.add_table(rows=1, cols=2)
            table.style = "Light Grid Accent 1"

            # Set column widths
            table.columns[0].width = Inches(3.0)
            table.columns[1].width = Inches(3.5)

            # Header row
            header_cells = table.rows[0].cells
            header_cells[0].text = "Original Claim"
            header_cells[1].text = "Counterarguments"

            # Style header
            for cell in header_cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.bold = True
                        run.font.size = Pt(12)
                # Set background color (light blue)
                self._set_cell_background(cell, "D9E9F7")

            # Add content row
            row = table.add_row()
            cells = row.cells

            # Claim cell
            claim_paragraph = cells[0].paragraphs[0]
            claim_paragraph.text = claim.text
            claim_paragraph.style = "Normal"

            # Add claim metadata
            meta_paragraph = cells[0].add_paragraph()
            meta_run = meta_paragraph.add_run(
                f"\n[Type: {claim.claim_type} | Confidence: {claim.confidence:.1%}]"
            )
            meta_run.font.size = Pt(9)
            meta_run.font.color.rgb = RGBColor(128, 128, 128)
            meta_run.italic = True

            # Counterargument cell
            counter_paragraph = cells[1].paragraphs[0]
            counter_paragraph.text = claim.counterargument or "No counterargument generated."
            counter_paragraph.style = "Normal"

            # Add spacing after table
            doc.add_paragraph()

        # Add footer with timestamp
        doc.add_page_break()
        footer_section = doc.add_paragraph()
        footer_section.add_run(
            f"\nGenerated by Legal Writing Tool on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ).italic = True

        # Save document
        doc.save(str(output_path))
        logger.info(f"Successfully wrote {len(claims_with_counter)} claims to {output_path}")

    def write_sequential_format(self, legal_doc: LegalDocument, output_path: Path) -> None:
        """Write document in sequential format with markers.

        Args:
            legal_doc: LegalDocument with claims and counterarguments
            output_path: Path where output document will be saved
        """
        logger.info(f"Writing output document (sequential format) to: {output_path}")

        doc = Document()

        # Add title
        title = doc.add_heading("Legal Argument Analysis - Counterarguments", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add metadata
        self._add_metadata_section(doc, legal_doc)

        doc.add_paragraph()

        # Get claims with counterarguments
        claims_with_counter = legal_doc.get_claims_with_counterarguments()

        if not claims_with_counter:
            doc.add_paragraph("No counterarguments were generated.")
            doc.save(str(output_path))
            return

        # Write each claim and counterargument
        for idx, claim in enumerate(claims_with_counter, 1):
            # Claim heading
            doc.add_heading(f"Claim {idx}", level=2)

            # Original claim
            claim_label = doc.add_paragraph()
            claim_label.add_run("ORIGINAL CLAIM:").bold = True

            claim_text = doc.add_paragraph(claim.text)
            claim_text.style = "Quote"

            # Counterargument
            counter_label = doc.add_paragraph()
            counter_label.add_run("COUNTERARGUMENTS:").bold = True

            counter_text = doc.add_paragraph(claim.counterargument or "No counterargument.")

            # Add spacing
            doc.add_paragraph()
            doc.add_paragraph("─" * 80)
            doc.add_paragraph()

        # Save
        doc.save(str(output_path))
        logger.info(f"Successfully wrote {len(claims_with_counter)} claims to {output_path}")

    def _add_metadata_section(self, doc: Document, legal_doc: LegalDocument) -> None:
        """Add metadata section to document.

        Args:
            doc: Document object to add metadata to
            legal_doc: Source legal document
        """
        meta = legal_doc.metadata

        meta_para = doc.add_paragraph()
        meta_para.add_run("Source Document: ").bold = True
        meta_para.add_run(meta.file_path.name)

        meta_para = doc.add_paragraph()
        meta_para.add_run("Total Claims Found: ").bold = True
        meta_para.add_run(str(meta.total_claims))

        meta_para = doc.add_paragraph()
        meta_para.add_run("Claims with Counterarguments: ").bold = True
        meta_para.add_run(str(len(legal_doc.get_claims_with_counterarguments())))

        if meta.processing_timestamp:
            meta_para = doc.add_paragraph()
            meta_para.add_run("Processed: ").bold = True
            meta_para.add_run(meta.processing_timestamp)

    def _set_cell_background(self, cell, color: str) -> None:
        """Set background color of a table cell.

        Args:
            cell: Table cell
            color: Hex color code (without #)
        """
        from docx.oxml import parse_xml
        from docx.oxml.ns import nsdecls

        shading_elm = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{color}"/>')
        cell._element.get_or_add_tcPr().append(shading_elm)
